// vue-app/src/components/Booth.vue
<template>
  <div>
    <button
      v-for="(option, index) in options"
      :key="option"
      class="m5"
      @click="$emit('onVote', index)"
    >
      {{ option }}
    </button>
  </div>
</template>

<script>
export default {
  props: ["options"],
};
</script>

<style>
.m5 {
  margin: 5px;
}
</style>

// react-app/src/components/booth.js
import PropTypes from 'prop-types';
import './style.css';

export default function Booth(props) {
    const options = props.options.map((option, index) => (
        <button key={option} className={'m5'} onClick={() => props.onVote(index)}>
            {option}
        </button>
    ))

    return (
        <div>
            {options}
        </div>
    )
}

Booth.propTypes = {
    onVote: PropTypes.func,
    options: PropTypes.array,
};
