// angular-app/src/components/votingCard.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'votingCard',
    template: `
    <div class="votingCard" *ngIf="state === 'open'; else results">
        <h3>{{title}}</h3>
        <booth [options]="options" (onVote)="onVote($event)"></booth>
    </div>
    <ng-template #results>
        <div class="votingCard">
            <h3>{{title}}</h3>
            <result [votes]="votes"></result>
        </div>
    </ng-template>
  `,
    styleUrls: ['./style.css'],
})

export class VotingCardComponent {
    @Input() title!: string;
    @Input() votes!: { option: string; count: number; }[];
    @Input() state!: string;
    options: string[] = [];
    ngOnInit() {
        for (var i = 0; i < this.votes.length; i++) {
            this.options[i] = this.votes[i].option;
        }
    }
    onVote(index: number) {
        this.state = 'close';
        this.votes[index].count++;
    }
}

// react-app/src/components/votingCard.js
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import './style.css';
import Booth from './booth';
import Result from './result';

export default function VotingCard(props) {
    const options = props.votes.map((votes) => (
        votes.option
    ))
    const [state, setState] = useState(props.state);
    useEffect(() => {
        if (props.state !== state) {
            setState(props.state)
        }
    }, [props.state])

    function vote(optionIndex) {
        setState('close');
        props.votes[optionIndex].count++;
    }
    const panel = state === 'open' ? (
        <div className={'votingCard'}>
            <h3>{props.title}</h3>
            <Booth options={options} onVote={vote} />
        </div>
    ) : (
        <div className={'votingCard'}>
            <h3>{props.title}</h3>
            <Result votes={props.votes} />
        </div>
    )

    return (
        panel
    )
}

VotingCard.propTypes = {
    title: PropTypes.string,
    state: PropTypes.string,
    votes: PropTypes.array,
};
