// react-app/src/components/result.js
import React from 'react';
import PropTypes from 'prop-types';

export default function Result(props) {
    const reducer = (accumulator, currentValue) => accumulator + currentValue;
    const arrayCount = props.votes.map((votes, index) => (
        votes.count
    ))
    const votesTotal = arrayCount.reduce(reducer);
    const answers = props.votes.map((votes, index) => (
        <p key={index.toString()}>
            {index + 1}. {votes.option} - {votes.count} votes ({votes.count * 100 / votesTotal}%)
        </p>
    ))
    return (
        <div>
            {answers}
        </div>
    )
}

Result.propTypes = {
    votes: PropTypes.array,
};

// vue-app/src/components/Result.vue
<template>
  <div>
    <p v-for="(vote, index) in votes" :key="index.toString()">
      {{ index + 1 }}. {{ vote.option }} - {{ vote.count }} votes ({{
        (vote.count * 100) / calculaVotesTotal
      }}%)
    </p>
  </div>
</template>

<script>
export default {
  props: ["votes"],
  data: () => ({
    votesTotal: 0,
  }),
  computed: {
    calculaVotesTotal() {
      for (var i = 0; i < this.votes.length; i++) {
        this.votesTotal += this.votes[i].count;
      }
      return this.votesTotal;
    },
  },
};
</script>

<style>
.m5 {
  margin: 5px;
}
</style>
