// react-app/src/components/votingCard.js
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import './style.css';
import Booth from './booth';
import Result from './result';

export default function VotingCard(props) {
    const options = props.votes.map((votes) => (
        votes.option
    ))
    const [state, setState] = useState(props.state);
    useEffect(() => {
        if (props.state !== state) {
            setState(props.state)
        }
    }, [props.state])

    function vote(optionIndex) {
        setState('close');
        props.votes[optionIndex].count++;
    }
    const panel = state === 'open' ? (
        <div className={'votingCard'}>
            <h3>{props.title}</h3>
            <Booth options={options} onVote={vote} />
        </div>
    ) : (
        <div className={'votingCard'}>
            <h3>{props.title}</h3>
            <Result votes={props.votes} />
        </div>
    )

    return (
        panel
    )
}

VotingCard.propTypes = {
    title: PropTypes.string,
    state: PropTypes.string,
    votes: PropTypes.array,
};

// svelte-app/src/components/VotingCard.svelte
<script>
    import Booth from "./Booth.svelte";
    import Result from "./Result.svelte";
    export let votes;
    export let title;
    export let state;
    $: options = votes.map((vote) => vote.option);
    function onVote(index) {
        state = "close";
        votes[index].count++;
    }
</script>

{#if state === "open"}
    <div class="votingCard">
        <h3>{title}</h3>
        <Booth {options} {onVote} />
    </div>
{:else}
    <div class="votingCard">
        <h3>{title}</h3>
        <Result {votes} />
    </div>
{/if}

<style>
    .votingCard {
        background-color: rgb(166, 200, 224);
        border: 1px solid black;
        border-radius: 10px;
    }
</style>
