// vue-app/src/components/Booth.vue
<template>
  <div>
    <button
      v-for="(option, index) in options"
      :key="option"
      class="m5"
      @click="$emit('onVote', index)"
    >
      {{ option }}
    </button>
  </div>
</template>

<script>
export default {
  props: ["options"],
};
</script>

<style>
.m5 {
  margin: 5px;
}
</style>

// angular-app/src/components/booth.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'booth',
  template: `
  <button class="m5" *ngFor="let option of options; index as i" (click)="onVote.emit(i)">
    {{option}}
  </button>
  `,
  styleUrls: ['./style.css'],
})
export class BoothComponent {
  @Input() options!: string[];
  @Output() onVote = new EventEmitter<number>()
}
